<a href="https://colab.research.google.com/github/alonacode/AI/blob/main/My_of_DZ_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [3]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [5]:
f = np.arange(30,71,2)
f

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [13]:
numbers = np.linspace(0., 0.9, num=10)
print(numbers)
# або

array = np.random.rand(10)

print(array)



[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.91061369 0.23700675 0.34070982 0.23517119 0.761794   0.22963594
 0.31537629 0.94757636 0.57024876 0.48563449]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [19]:
matrix = np.array([
    [1, 2],
    [3, 4]
])



# Створюємо нову матрицю розміру (n+2) x (n+2), заповнену нулями
padded_matrix = np.zeros((4, 4), dtype=matrix.dtype)

# Вставляємо оригінальну матрицю в центр нової матриці
padded_matrix[1:-1, 1:-1] = matrix

print(padded_matrix)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [20]:
print("Тип даних до зміни:", padded_matrix.dtype)

padded_matrix_float = padded_matrix.astype(float)

print("Тип даних після зміни:", padded_matrix_float.dtype)

print("Масив з новим типом даних:")
print(padded_matrix_float)

Тип даних до зміни: int64
Тип даних після зміни: float64
Масив з новим типом даних:
[[0. 0. 0. 0.]
 [0. 1. 2. 0.]
 [0. 3. 4. 0.]
 [0. 0. 0. 0.]]


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [37]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

original_x = x.copy()
mask_equal = (original_x == var)
x[mask_equal] = -1
print(x)

x = original_x.copy()
mask_less = (x < var)
x[mask_less] = -1
print(x)

x = original_x.copy()
mask_more = (x > var)
x[mask_more] = -1
print(x)

x = original_x.copy()
x[(x == var) | (x >= var) | (x <= var)] = -1
print("Масив після заміни всіх трьох випадків:")
print(x)

[ 1 -1  3  8  6 -1  7  4]
[-1  5 -1  8  6  5  7 -1]
[ 1  5  3 -1 -1  5 -1  4]
Масив після заміни всіх трьох випадків:
[-1 -1 -1 -1 -1 -1 -1 -1]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [39]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

mask_nan = np.isnan(X)
X[mask_nan] = -1

print("Масив після заміни пропущених значень на -1:")
print(X)

Масив після заміни пропущених значень на -1:
[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [41]:
x = np.random.random((4,6))
y = np.reshape(x, (3,8))
print(y)

[[0.78093661 0.80692495 0.94121331 0.4756987  0.52178401 0.15573515
  0.4294614  0.94740141]
 [0.18966987 0.68229572 0.02863346 0.3896562  0.60211318 0.27384583
  0.2508646  0.26491664]
 [0.1513297  0.47218483 0.46317609 0.90415156 0.4949007  0.67633114
  0.6364132  0.39755584]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [45]:
x = np.ones((3, 4))
mean_per_column = np.mean(x, axis=0)
mean_per_column

array([1., 1., 1., 1.])

#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [53]:
x = np.random.random((5,6))
print(x)
matrix_rounded = np.round(x, 1)

print("Матриця після округлення:")
print(matrix_rounded)

sorted_indices = np.argsort(matrix_rounded[0, :])
print("Індекси :")
print(sorted_indices)

sorted_matrix = matrix_rounded[:, sorted_indices]
sorted_matrix

[[0.40726309 0.58478325 0.46997943 0.30838369 0.08180808 0.58256952]
 [0.68814273 0.28675161 0.50393454 0.77623166 0.70584827 0.3294029 ]
 [0.03678513 0.90976143 0.54365397 0.37831774 0.05206438 0.99995526]
 [0.23696832 0.61699761 0.94030639 0.12795527 0.30655736 0.93519408]
 [0.01444395 0.09904274 0.90795919 0.45856191 0.56858807 0.50623408]]
Матриця після округлення:
[[0.4 0.6 0.5 0.3 0.1 0.6]
 [0.7 0.3 0.5 0.8 0.7 0.3]
 [0.  0.9 0.5 0.4 0.1 1. ]
 [0.2 0.6 0.9 0.1 0.3 0.9]
 [0.  0.1 0.9 0.5 0.6 0.5]]
Індекси :
[4 3 0 2 1 5]


array([[0.1, 0.3, 0.4, 0.5, 0.6, 0.6],
       [0.7, 0.8, 0.7, 0.5, 0.3, 0.3],
       [0.1, 0.4, 0. , 0.5, 0.9, 1. ],
       [0.3, 0.1, 0.2, 0.9, 0.6, 0.9],
       [0.6, 0.5, 0. , 0.9, 0.1, 0.5]])

#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [57]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])

mask = np.logical_and(X >= 3, X <= 6)
print(mask)

filtered_values = X[mask]

print("\nЕлементи між 3 і 6:")
print(filtered_values)

[[False False  True  True  True]
 [ True False False False False]
 [False False False  True  True]
 [ True  True False False False]]

Елементи між 3 і 6:
[3 4 5 6 6 5 4 3]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [67]:
x = np.random.random((5,6))
print("Створена матриця", x)
min_values = np.min(x, axis=0)
print("MIN",min_values)
max_values = np.max(x, axis=0)
print("MAX",max_values)
# Нормалізована матриця
normalized_matrix = (x - min_values) / (max_values - min_values)

print("Нормалізована матриця:")
print(normalized_matrix)

Створена матриця [[0.41035568 0.85896314 0.97879155 0.49471031 0.78866446 0.1969187 ]
 [0.37828518 0.987238   0.70935098 0.42187703 0.88927825 0.79321575]
 [0.92867645 0.98170428 0.64329116 0.91383378 0.07657178 0.8517977 ]
 [0.99608948 0.30740041 0.54094898 0.48294671 0.76112109 0.92175006]
 [0.33503508 0.62070626 0.10826271 0.49010207 0.23008423 0.64897332]]
MIN [0.33503508 0.30740041 0.10826271 0.42187703 0.07657178 0.1969187 ]
MAX [0.99608948 0.987238   0.97879155 0.91383378 0.88927825 0.92175006]
Нормалізована матриця:
[[0.1139401  0.81131543 1.         0.14804814 0.87619911 0.        ]
 [0.06542593 1.         0.69048634 0.         1.         0.82267005]
 [0.89802196 0.99186023 0.61460164 1.         0.         0.90349154]
 [1.         0.         0.49703841 0.12413628 0.84230819 1.        ]
 [0.         0.46085397 0.         0.13868096 0.18889041 0.62366869]]
