<a href="https://colab.research.google.com/github/alonacode/AI/blob/main/Practice_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [9]:
import numpy as np


# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [17]:
x = np.arange(1, 13)
print(x, x.shape, x.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,) int64


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

In [19]:
new_x = x.reshape((3, 4))
new_x = new_x.astype(np.float32)

print(new_x.T)

[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]


#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [26]:
chess_board = np.zeros((8, 8), dtype=np.int8)

chess_board[1::2, ::2] = 1
chess_board[::2, 1::2] = 1

print(chess_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [36]:
x = np.random.random((4,3))
print(x)
print("All",np.sum(x))
print("Row:", np.sum(x, axis=1))
print("Column:", np.sum(x, axis=0))

[[0.68376935 0.09102731 0.19190479]
 [0.48107331 0.85850972 0.63431488]
 [0.20456855 0.31203576 0.02380707]
 [0.30154048 0.12779205 0.30988802]]
All 4.220231294967168
Row: [0.96670145 1.97389792 0.54041137 0.73922055]
Column: [1.67095169 1.38936484 1.15991477]


# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

In [37]:
max_row = x.max(axis=1, keepdims=True)

new_x = x - max_row

new_x

array([[ 0.        , -0.59274203, -0.49186456],
       [-0.37743641,  0.        , -0.22419484],
       [-0.10746721,  0.        , -0.28822868],
       [-0.00834754, -0.18209597,  0.        ]])

# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

In [38]:
weight = np.array([5, 10, 25, 40])
count = np.array([20, 5, 10, 4])

total = weight @ count
total

560

# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.

In [43]:
weight = np.array([5, 10, 25, 40])
count = np.array([
                  [20, 5, 10, 4],
                  [10, 5, 6,  7],
                  [2, 3, 4, 7],
                ])
total = count @ weight
total

array([560, 530, 420])